Computar la norma y el número de condición de Frobenius

In [5]:
import numpy as np

In [9]:
m = np.arange(1, 17).reshape(4,4)
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
np.linalg.norm(m, 'fro')

38.67815921162743

In [11]:
np.linalg.cond(m, 'fro')

inf

video 2:

In [12]:
from numpy import sqrt

In [13]:
print("Programa para el calculo de la norma infinito y frobenius para una matriz NxN")

Programa para el calculo de la norma infinito y frobenius para una matriz NxN


In [14]:
#Variables y matrices
n = 7
M = np.random.randint(9, size=(n,n))
print('La matriz de N*N es:', M)

La matriz de N*N es: [[4 8 2 7 4 8 2]
 [2 1 4 2 4 4 1]
 [5 8 6 6 7 0 7]
 [4 6 7 3 3 6 7]
 [4 6 1 3 7 3 5]
 [6 7 6 7 1 0 7]
 [3 8 6 5 7 8 1]]


In [18]:
#lista
sumatoria_columnas = []
sumatoria_filas = []
sumatoria_frobenius = []

#Definir funciones para columnas:
print("n -> para columnas")
def columna(n):
    suma=0
    for i in range(0,n):
        y=M[i,:]
        suma=abs(suma+y)
        normac=suma
        
        sumatoria_columnas.append(i)
        return normac
    
    print('normac', normac)
    
print('la norma de las columnas respectivamente es:', columna(n))

#valor maximo de la norma
maxcolumna=np.max(columna(n))
print('El valor maximo de las normas de las columnas es:', maxcolumna)

n -> para columnas
la norma de las columnas respectivamente es: [4 8 2 7 4 8 2]
El valor maximo de las normas de las columnas es: 8


In [33]:
# definir función para filas
print('n -> para filas')

def fila(n):
    suma=0
    for j in range(0,n):
        x=M[:,j]
        suma=abs(suma+x)
        normaf=suma
        
        sumatoria_filas.append(j)
        
        return normaf
    
print('la norma de las filas respectivamente es: ', fila(n))
    
 #valor maximo de la norma
maxfila=np.max(columna(n))
print('El valor maximo de las normas de las columnas es:', maxfila)

n -> para filas
la norma de las filas respectivamente es:  [4 2 5 4 4 6 3]
El valor maximo de las normas de las columnas es: 8


Definir la norma de frobenius

In [36]:
print('n -> norma de Frobenius')
def normfrobenius():
    suma=0
    for filas in M:
        for elementos in filas:
            cuadrado=elementos**2
            suma += cuadrado
            return sqrt(suma)
        
print('la norma de frobenius respectivamente es: ', normfrobenius())

    

n -> norma de Frobenius
la norma de frobenius respectivamente es:  4.0


Video 3.

In [44]:
#Variables y matrices
n = 2
M = np.random.randint(4, size=(n,n))
print(M)

[[2 3]
 [1 1]]


In [41]:
(3**2 + 1**2 + 1**2 + 2**2)**(1/2)

3.872983346207417

Norm using numpy directly

In [42]:
np.linalg.norm(M)

3.872983346207417

use torch.norm() if there's float type.